# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import example_pb2 as example__pb2


class ExampleStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getGithubUrl = channel.unary_unary(
                '/example.Example/getGithubUrl',
                request_serializer=example__pb2.request.SerializeToString,
                response_deserializer=example__pb2.userGithub.FromString,
                )
        self.getMessage = channel.unary_unary(
                '/example.Example/getMessage',
                request_serializer=example__pb2.request.SerializeToString,
                response_deserializer=example__pb2.userGithubMessage.FromString,
                )


class ExampleServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getGithubUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExampleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getGithubUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.getGithubUrl,
                    request_deserializer=example__pb2.request.FromString,
                    response_serializer=example__pb2.userGithub.SerializeToString,
            ),
            'getMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.getMessage,
                    request_deserializer=example__pb2.request.FromString,
                    response_serializer=example__pb2.userGithubMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.Example', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Example(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getGithubUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Example/getGithubUrl',
            example__pb2.request.SerializeToString,
            example__pb2.userGithub.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.Example/getMessage',
            example__pb2.request.SerializeToString,
            example__pb2.userGithubMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
