# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\x12\x07\x65xample\"\'\n\x07request\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06github\x18\x02 \x01(\t\"\x19\n\nuserGithub\x12\x0b\n\x03url\x18\x01 \x01(\t\" \n\x11userGithubMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x80\x01\n\x07\x45xample\x12\x37\n\x0cgetGithubUrl\x12\x10.example.request\x1a\x13.example.userGithub\"\x00\x12<\n\ngetMessage\x12\x10.example.request\x1a\x1a.example.userGithubMessage\"\x00\x62\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='example.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.request.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='github', full_name='example.request.github', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=65,
)


_USERGITHUB = _descriptor.Descriptor(
  name='userGithub',
  full_name='example.userGithub',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='example.userGithub.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=92,
)


_USERGITHUBMESSAGE = _descriptor.Descriptor(
  name='userGithubMessage',
  full_name='example.userGithubMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='example.userGithubMessage.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['userGithub'] = _USERGITHUB
DESCRIPTOR.message_types_by_name['userGithubMessage'] = _USERGITHUBMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.request)
  })
_sym_db.RegisterMessage(request)

userGithub = _reflection.GeneratedProtocolMessageType('userGithub', (_message.Message,), {
  'DESCRIPTOR' : _USERGITHUB,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.userGithub)
  })
_sym_db.RegisterMessage(userGithub)

userGithubMessage = _reflection.GeneratedProtocolMessageType('userGithubMessage', (_message.Message,), {
  'DESCRIPTOR' : _USERGITHUBMESSAGE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.userGithubMessage)
  })
_sym_db.RegisterMessage(userGithubMessage)



_EXAMPLE = _descriptor.ServiceDescriptor(
  name='Example',
  full_name='example.Example',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=129,
  serialized_end=257,
  methods=[
  _descriptor.MethodDescriptor(
    name='getGithubUrl',
    full_name='example.Example.getGithubUrl',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_USERGITHUB,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getMessage',
    full_name='example.Example.getMessage',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_USERGITHUBMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXAMPLE)

DESCRIPTOR.services_by_name['Example'] = _EXAMPLE

# @@protoc_insertion_point(module_scope)
