# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ntest.proto\x12\x07\x65xample\"e\n\x07testreq\x12\x0c\n\x04user\x18\x01 \x01(\t\x12#\n\x04role\x18\x02 \x01(\x0e\x32\x15.example.testreq.Role\"\'\n\x04Role\x12\t\n\x05\x41\x44MIN\x10\x00\x12\x08\n\x04USER\x10\x01\x12\n\n\x06\x44RIVER\x10\x02\"\x1c\n\x08testresp\x12\x10\n\x08userRole\x18\x01 \x01(\t28\n\x04Test\x12\x30\n\x07TestApi\x12\x10.example.testreq\x1a\x11.example.testresp\"\x00\x62\x06proto3'
)



_TESTREQ_ROLE = _descriptor.EnumDescriptor(
  name='Role',
  full_name='example.testreq.Role',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ADMIN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='USER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DRIVER', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=85,
  serialized_end=124,
)
_sym_db.RegisterEnumDescriptor(_TESTREQ_ROLE)


_TESTREQ = _descriptor.Descriptor(
  name='testreq',
  full_name='example.testreq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='example.testreq.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='role', full_name='example.testreq.role', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TESTREQ_ROLE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=124,
)


_TESTRESP = _descriptor.Descriptor(
  name='testresp',
  full_name='example.testresp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userRole', full_name='example.testresp.userRole', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=154,
)

_TESTREQ.fields_by_name['role'].enum_type = _TESTREQ_ROLE
_TESTREQ_ROLE.containing_type = _TESTREQ
DESCRIPTOR.message_types_by_name['testreq'] = _TESTREQ
DESCRIPTOR.message_types_by_name['testresp'] = _TESTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

testreq = _reflection.GeneratedProtocolMessageType('testreq', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQ,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:example.testreq)
  })
_sym_db.RegisterMessage(testreq)

testresp = _reflection.GeneratedProtocolMessageType('testresp', (_message.Message,), {
  'DESCRIPTOR' : _TESTRESP,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:example.testresp)
  })
_sym_db.RegisterMessage(testresp)



_TEST = _descriptor.ServiceDescriptor(
  name='Test',
  full_name='example.Test',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=156,
  serialized_end=212,
  methods=[
  _descriptor.MethodDescriptor(
    name='TestApi',
    full_name='example.Test.TestApi',
    index=0,
    containing_service=None,
    input_type=_TESTREQ,
    output_type=_TESTRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEST)

DESCRIPTOR.services_by_name['Test'] = _TEST

# @@protoc_insertion_point(module_scope)
